app_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: qburst
    MYSQL_DATABASE: devops
  ports:
    - 9001:3306

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - app_db:mysql
  ports:
    - 9000:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: qburst
